### ISSUE TITLE
Unable to start plugin

### ISSUE THREAD

**Issue by martincijsouw** [Skons/hassio-addons#65]
Anyone else facing issues with starting the dutch gas prices addon? I cant start the plugin anymore with a fully updated HA instance.

-----------------------------------------------------------
 Add-on: Dutch gas prices
 Get gas prices from dutch gas stations
-----------------------------------------------------------
 Add-on version: 2024.01.25.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.5  (amd64 / qemux86-64)
 Home Assistant Core: 2024.2.2
 Home Assistant Supervisor: 2024.02.0
 
[16:46:38] INFO: Log_level: debug
[16:46:38] INFO: mqtt_host: XXXX
[16:46:38] INFO: mqtt_port: 1883
[16:46:38] DEBUG: mqtt_username: XXX
[16:46:38] DEBUG: mqtt_password: XXX
[16:46:38] INFO: Starting dutch gas prices...
[2024-02-21 16:46:42] DEBUG   : gas_station: Cachepath is '/app/cache/'
[2024-02-21 16:46:42] INFO    : DGP initialized, launching client
[2024-02-21 16:46:42] INFO    : Connecting to mqtt host 'XXX' with clientname 'f5a8083e-dutch-gas-prices'
Traceback (most recent call last):
  File "/app/main.py", line 23, in <module>
    start(str(sys.argv[1]),str(sys.argv[2]),str(sys.argv[3]),str(sys.argv[4]),str(sys.argv[5]))
  File "/app/main.py", line 16, in start
    start_mqtt_client(mqtthost,mqttport,mqttusername,mqttpassword)
  File "/app/mqtt_client.py", line 394, in start_mqtt_client
    mqtt_client = mqtt.Client(mqtt_client_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 766, in __init__
    raise ValueError(
_ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details_

**Comment by Jaspils** [comment]
Same for me.

I have another Home Assistance instance running the same Hass version (2024.2.2) but running an older add-on version (2023.4.26.1). The old one still works, isn't updated because the update-process is somehow broken. But since it's working as expected no need to fix it.

The new (broken) add-on is running version 2024.01.25.1. This one is running on the same Hass version (2024.2.2).

**Comment by Wxam** [comment]
I also have the same issue with the newest version of the add-on.
the plugin will start for a split second and just stop with the same message as OP has.

**Comment by Skons** [comment]
Fix just released, thanks @MWeesenaar!
