### ISSUE TITLE
Won't get new lpg price 

### ISSUE THREAD

**Issue by Dutchy-79** [Skons/hassio-addons#70]
It's been a while since I got the latest price.

Automation runs but there is a error in the addon log.

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------

 Add-on: Dutch gas prices
 Get gas prices from dutch gas stations
-----------------------------------------------------------
 Add-on version: 2024.2.29.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.3.1
 Home Assistant Supervisor: 2024.03.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[23:25:26] INFO: Log_level: info
[23:25:26] INFO: mqtt_host: core-mosquitto
[23:25:26] INFO: mqtt_port: 1883
[23:25:26] INFO: Starting dutch gas prices...
[2024-03-20 23:25:27] INFO    : DGP initialized, launching client
[2024-03-20 23:25:27] INFO    : Connecting to mqtt host 'core-mosquitto' with clientname 'f5a8083e-dutch-gas-prices'
[2024-03-20 23:25:27] INFO    : Using username 'mqtt_username' to connect to 'core-mosquitto'
[2024-03-20 23:25:27] INFO    : Connected with result code '0'
[2024-03-20 23:26:17] INFO    : Received payload '{"station_id":3580,"fuel_type":"lpg"}' on topic 'dgp/gas_station'
[2024-03-20 23:26:18] ERROR   : _write_stationdata '3580': statuscode '403'
[2024-03-20 23:26:18] ERROR   : _write_stationdata '3580': Used header '{'Accept': '*/*', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36 OPR/56.0.3051.99'}'
[2024-03-20 23:26:18] ERROR   : _write_stationdata '3580': Used IP '62.45.117.81'
[2024-03-20 23:26:18] ERROR   : _write_stationdata '3580': Response text '<html><head><title>Apache Tomcat/7.0.76 - Error report</title><style></style> </head><body><h1>HTTP Status 403 - Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.76</h3></body></html>'
[2024-03-20 23:26:18] ERROR   : _write_allstationdata: statuscode '403'
[2024-03-20 23:26:18] ERROR   : _write_allstationdata: Used header '{'Accept': '*/*', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36 OPR/56.0.3051.99'}'
[2024-03-20 23:26:18] ERROR   : _write_allstationdata: Used IP '62.45.117.81'
[2024-03-20 23:26:18] ERROR   : _write_allstationdata: Response text '<html><head><title>Apache Tomcat/7.0.76 - Error report</title><style></style> </head><body><h1>HTTP Status 403 - Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.76</h3></body></html>'
[2024-03-20 23:26:18] INFO    : publishing station_id None to mqtt
Exception in thread Thread-1 (publish_station):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mqtt_client.py", line 174, in publish_station
    stationtopic = f"{station_info['station_id']}_{station_info['fuel_type']}"
                                                   ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'fuel_type'`

**Comment by Skons** [comment]
Please take a look at #63
